Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 4
Rules claiming more threads will be scaled down.
Job stats:
job                 count    min threads    max threads
----------------  -------  -------------  -------------
varsel_pol_model        1              1              1
total                   1              1              1

Select jobs to execute...

[Tue Jan 11 13:28:32 2022]
rule varsel_pol_model:
    input: ../results/models/td_ref_pol_fit.rds, ../results/processed_data/pol_dat.rds
    output: ../results/models/varsel_td_pol.rds
    log: ../results/logs/02_varsel_ref_pol_model.log
    jobid: 0
    resources: tmpdir=/var/folders/hl/dt523djx7_q7xjrthzjpdvc40000gn/T

[Tue Jan 11 13:46:53 2022]
Error in rule varsel_pol_model:
    jobid: 0
    output: ../results/models/varsel_td_pol.rds
    log: ../results/logs/02_varsel_ref_pol_model.log (check log file(s) for error message)

RuleException:
CalledProcessError in line 14 of /Users/corrado/_repositories/fake_news_wf/fake_news/workflow/rules/varsel_ref_pol_td.smk:
Command 'set -euo pipefail;  Rscript --vanilla /Users/corrado/_repositories/fake_news_wf/fake_news/workflow/.snakemake/scripts/tmp_mz_ny9e.02_td_varsel_ref_pol_model.R' returned non-zero exit status 1.
  File "/Users/corrado/_repositories/fake_news_wf/fake_news/workflow/rules/varsel_ref_pol_td.smk", line 14, in __rule_varsel_pol_model
  File "/opt/anaconda3/lib/python3.8/concurrent/futures/thread.py", line 57, in run
Removing output files of failed job varsel_pol_model since they might be corrupted:
../results/models/varsel_td_pol.rds
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /Users/corrado/_repositories/fake_news_wf/fake_news/workflow/.snakemake/log/2022-01-11T132832.348591.snakemake.log
